package com.baeldung.drools.rules;

import com.baeldung.drools.model.Applicant;
import com.baeldung.drools.model.Temp;

global com.baeldung.drools.model.SuggestedRole suggestedRole;

dialect  "mvel"

rule "Suggest Temp"
    when
        Applicant(experienceInYears > 10)
    then
        Temp temp = new Temp();
        temp.setT(19);
        insert(temp)
end

rule "Suggest manager basing on Temp"
    when
        Temp(t > 0)
    then
        suggestedRole.setRole("Manager123");
end

//rule "Suggest Senior developer Role"
//    when
//        Applicant(experienceInYears > 5 && experienceInYears <= 10)
//        Applicant(currentSalary > 500000 && currentSalary <= 1500000)
//    then
//        suggestedRole.setRole("Senior developer");
//end
//
//rule "Suggest Developer Role"
//    when
//        Applicant(experienceInYears > 0 && experienceInYears <= 5)
//        Applicant(currentSalary > 200000 && currentSalary <= 1000000)
//    then
//        suggestedRole.setRole("Developer");
//end
